CREATE DATABASE SQL_BAITAP01
GO
USE SQL_BAITAP01 
GO
CREATE TABLE KHOA
(MaKH char(2),
TenKH nvarchar(50),
PRIMARY KEY(MaKH)
)
GO
CREATE TABLE MON(
MaMH char(2),
TenMH nvarchar(50),
Sotiet int,
PRIMARY KEY(MaMH)
)
GO
CREATE TABLE SINHVIEN(
MaSV char(2),
HoSV nvarchar(30),
TenSV nvarchar(20),
Phai bit,
NgaySinh datetime,
NoiSinh nvarchar(50),
MaKH char(2),
HocBong real,
 PRIMARY KEY (MaSV)
)
GO
DROP TABLE [dbo].[KETQUA]
GO
CREATE TABLE Ketqua(
MaSV char(2),
MaMH char(2),
Diem int,
PRIMARY KEY(MaSV,MaMH),
CONSTRAINT  Fk_Ketqua_SINHVIEN_MaSV FOREIGN KEY (MaSV) REFERENCES SINHVIEN(MaSV)
ON UPDATE CASCADE 
ON DELETE NO ACTION ,
CONSTRAINT Fk_Ketqua_MON_MaMH FOREIGN KEY (MaMH) REFERENCES MON(MaMH)
ON UPDATE CASCADE 
ON DELETE NO ACTION 
)
GO
---
